# Generated by Django 5.1.10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0022_normalize_localfiles_paths"),
        ("projects", "0001_squashed_0065_auto_20210223_2014"),
        ("tasks", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabricksVolumesImportStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync finished time",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Count of tasks synced last time",
                        null=True,
                        verbose_name="last sync count",
                    ),
                ),
                (
                    "last_sync_job",
                    models.CharField(
                        blank=True,
                        help_text="Last sync job ID",
                        max_length=256,
                        null=True,
                        verbose_name="last_sync_job",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="initialized",
                        max_length=64,
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback report for the last failed sync",
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Meta and debug information about storage processes",
                        null=True,
                        verbose_name="meta",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage title",
                        max_length=256,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "synchronizable",
                    models.BooleanField(
                        default=True,
                        help_text="If storage can be synced",
                        verbose_name="synchronizable",
                    ),
                ),
                (
                    "databricks_host",
                    models.TextField(
                        blank=True,
                        help_text="Databricks workspace URL (e.g. https://dbc-xxx.cloud.databricks.com)",
                        null=True,
                        verbose_name="databricks_host",
                    ),
                ),
                (
                    "databricks_client_id",
                    models.TextField(
                        blank=True,
                        help_text="Databricks Service Principal client ID",
                        null=True,
                        verbose_name="databricks_client_id",
                    ),
                ),
                (
                    "databricks_client_secret",
                    models.TextField(
                        blank=True,
                        help_text="Databricks Service Principal OAuth secret",
                        null=True,
                        verbose_name="databricks_client_secret",
                    ),
                ),
                (
                    "catalog",
                    models.TextField(
                        blank=True,
                        help_text="Unity Catalog catalog name",
                        null=True,
                        verbose_name="catalog",
                    ),
                ),
                (
                    "schema_name",
                    models.TextField(
                        blank=True,
                        help_text="Unity Catalog schema name",
                        null=True,
                        verbose_name="schema_name",
                    ),
                ),
                (
                    "volume",
                    models.TextField(
                        blank=True,
                        help_text="Unity Catalog volume name",
                        null=True,
                        verbose_name="volume",
                    ),
                ),
                (
                    "prefix",
                    models.TextField(
                        blank=True,
                        help_text="Path prefix within the volume",
                        null=True,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "regex_filter",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage regex for filtering objects",
                        null=True,
                        verbose_name="regex_filter",
                    ),
                ),
                (
                    "use_blob_urls",
                    models.BooleanField(
                        default=False,
                        help_text="Interpret objects as BLOBs and generate URLs",
                        verbose_name="use_blob_urls",
                    ),
                ),
                (
                    "recursive_scan",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Perform recursive scan over the volume content",
                        null=True,
                        verbose_name="recursive scan",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="A unique integer value identifying this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="io_storages_databricksvolumesimportstorages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatabricksVolumesExportStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last sync finished time",
                        null=True,
                        verbose_name="last sync",
                    ),
                ),
                (
                    "last_sync_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Count of tasks synced last time",
                        null=True,
                        verbose_name="last sync count",
                    ),
                ),
                (
                    "last_sync_job",
                    models.CharField(
                        blank=True,
                        help_text="Last sync job ID",
                        max_length=256,
                        null=True,
                        verbose_name="last_sync_job",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("queued", "Queued"),
                            ("in_progress", "In progress"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                        ],
                        default="initialized",
                        max_length=64,
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback report for the last failed sync",
                        null=True,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Meta and debug information about storage processes",
                        null=True,
                        verbose_name="meta",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Cloud storage title",
                        max_length=256,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "synchronizable",
                    models.BooleanField(
                        default=True,
                        help_text="If storage can be synced",
                        verbose_name="synchronizable",
                    ),
                ),
                (
                    "can_delete_objects",
                    models.BooleanField(
                        blank=True,
                        help_text="Deletion from storage enabled",
                        null=True,
                        verbose_name="can_delete_objects",
                    ),
                ),
                (
                    "databricks_host",
                    models.TextField(
                        blank=True,
                        help_text="Databricks workspace URL (e.g. https://dbc-xxx.cloud.databricks.com)",
                        null=True,
                        verbose_name="databricks_host",
                    ),
                ),
                (
                    "databricks_client_id",
                    models.TextField(
                        blank=True,
                        help_text="Databricks Service Principal client ID",
                        null=True,
                        verbose_name="databricks_client_id",
                    ),
                ),
                (
                    "databricks_client_secret",
                    models.TextField(
                        blank=True,
                        help_text="Databricks Service Principal OAuth secret",
                        null=True,
                        verbose_name="databricks_client_secret",
                    ),
                ),
                (
                    "catalog",
                    models.TextField(
                        blank=True,
                        help_text="Unity Catalog catalog name",
                        null=True,
                        verbose_name="catalog",
                    ),
                ),
                (
                    "schema_name",
                    models.TextField(
                        blank=True,
                        help_text="Unity Catalog schema name",
                        null=True,
                        verbose_name="schema_name",
                    ),
                ),
                (
                    "volume",
                    models.TextField(
                        blank=True,
                        help_text="Unity Catalog volume name",
                        null=True,
                        verbose_name="volume",
                    ),
                ),
                (
                    "prefix",
                    models.TextField(
                        blank=True,
                        help_text="Path prefix within the volume",
                        null=True,
                        verbose_name="prefix",
                    ),
                ),
                (
                    "regex_filter",
                    models.TextField(
                        blank=True,
                        help_text="Cloud storage regex for filtering objects",
                        null=True,
                        verbose_name="regex_filter",
                    ),
                ),
                (
                    "use_blob_urls",
                    models.BooleanField(
                        default=False,
                        help_text="Interpret objects as BLOBs and generate URLs",
                        verbose_name="use_blob_urls",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="A unique integer value identifying this project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="io_storages_databricksvolumesexportstorages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatabricksVolumesImportStorageLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.TextField(
                        help_text="External link key",
                        verbose_name="key",
                    ),
                ),
                (
                    "object_exists",
                    models.BooleanField(
                        default=True,
                        help_text="Whether object under external link still exists",
                        verbose_name="object exists",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "row_group",
                    models.IntegerField(
                        blank=True,
                        help_text="Parquet row group",
                        null=True,
                    ),
                ),
                (
                    "row_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Parquet row index, or JSON[L] object index",
                        null=True,
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="io_storages.databricksvolumesimportstorage",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="io_storages_databricksvolumesimportstoragelink",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatabricksVolumesExportStorageLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_exists",
                    models.BooleanField(
                        default=True,
                        help_text="Whether object under external link still exists",
                        verbose_name="object exists",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update time",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="io_storages_databricksvolumesexportstoragelink",
                        to="tasks.annotation",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="io_storages.databricksvolumesexportstorage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
